spring:
  application:
    name:
      TaskService
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      lettuce:
        pool:
          min-idle: 0
          max-active: 16
          max-wait: -1ms
          max-idle: 8
  cloud:
    nacos:
      discovery:
        service: TaskService
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/my_blog_taskDB?serverTimezone=UTC # ?前面是数据库名
    username: root
    password: OYyj0715
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never  # always 会清空数据库后继续运行
    properties:
      org:
        quartz:
          jobStore:
            isClustered: true # 开启集群
            # 持久化处理(事务管理)
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore #全路径
            #            # 数据库驱动代理
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
          threadPool:
            threadCount: 20 # 线程
          scheduler:
            instanceName: quartzScheduler # 通过一集群  多个节点名称必须相同
            instanceId: AUTO # 自动为同一集群设置id

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete #默认deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration: #配置打印MyBatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml
server:
  port: 8085
  tomcat:
    connection-timeout: -1 # 设置连接超时时间未无限
