spring:

  # 邮箱 服务配置
  mail:
    host: smtp.qq.com # 邮箱服务器地址
    port: 465
    protocol: smtp # 协议
    username: 3129544205@qq.com
    password: owiclgghelckdghc
    default-encoding: utf-8 # 邮件内容授权码
    properties: # 配置开启 邮箱ssl加密 否则会发送失败
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      lettuce:
        pool:
          min-idle: 0
          max-active: 16
          max-wait: -1ms
          max-idle: 8

  cloud:
    nacos:
      discovery:
        service: AdminService
        #server-addr: localhost:8848
        server-addr: localhost:8848
        ip: 47.120.35.205  # 部署
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # url: jdbc:mysql://localhost:3306/my_blog_adminDB?serverTimezone=UTC # ?前面是数据库名
    url: jdbc:mysql://localhost:3306/my_blog_admindb?serverTimezone=UTC # ?前面是数据库名
    username: root
    password: OYyj0715

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete #默认deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration: #配置打印MyBatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml
server:
  port: 8083
logging:
  config: classpath:logback.xml  #指定日志的配置信息
