spring:
  application:
    name: AIChatDemo
  mvc:
    async:
      request-timeout: 360000 # 设置线程没有超时时长
  cloud:
    nacos:
      discovery:
        service: AIChatDemoService
        server-addr: localhost:8848

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1  # 与本地模型名称对应

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/my_blog_ai?serverTimezone=UTC # ?前面是数据库名
    username: root
    password: OYyj0715

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml   #-----用这个 成功率高

server:
  port: 8084
